
# Giris

İspanya  Portekiz ve Türkiye ekonomileri yapısal olarak birbirlerine yakın performanslar sergilemektedir. Genç nüfus oranları, işsizlik rakamları, Kobilerin ekonomiye katkıları  ekonomilerin karakteristiklerindeki benzerlikleri ortaya koymaktadır. 

Çalışmada Batı Avrupa ülkeleri hakkında bilgiler verilerek ülkeler analiz edilmeye çalışılmıştır. Ülkeler analiz edilirken  nüfus yapısı, işsizlik oranları, işgücü yapısı, kobilerin istihdam payları, dış ticaret dengeleri, sektörlerin payları, uluslararası rekabet edebilirlik endeksi gibi faktörler incelenmiştir. Bu faktörlere göre ülkelerin performansları çeşitli otoritelerin resmi sayfalarından ve yayınlanmış raporlardan elde edilmiştir.

Avrupa Birliği Küçük İşletmeler Yasasına ( SBA-Small Business Act) göre girişimcilik, ikinci şans, küçük olanı düşün, duyarlı yönetim, devlet yardımları ve kamu alımları, finans, tek pazar, yetenekler  ve yenilik, çevre, globalleşme  ölçüm kriteri olarak belirlenmiştir. Ülkelerin işletmelerinin performansları bu kriterler göz önüne alınarak değerlendirilmeye çalışmıştır.

Ülkelerin kobilere sağladıkları destekler ortaya konularak, destekleri sağlayan kamu otoriteleri tanıtılmıştır.

 Sonuç bölümünde politika önerilerinde bulunularak, çalışmanın genel değerlendirmesi yapılmıştır.




