
# Sonuc ve Oneriler

Küçük ve orta boylu işletmelerin incelenen ülke ekonomileri açısından önemi sayısal veriler dikkate alınarak incelendiğinde ortaya çıkmaktadır. İstihdam payları, ürettikleri katma değerler gözönüne alındığında  ekonomilerinin temel taşlarından birisi haline geldikleri analiz edilmektedir. Dolayısıyla Kobi tanımına uyan işletmeler üzerinde üretilen politikaların etkileri  ve ekonomilerin genel görünümü üzerindeki tepkileri  dikkatle etüd edilmesi gerekmektedir.

Türkiye’nin AB Komisyonu Kobi yasası incelemelerine göre girişimcilik konusunda iyileştirmelerin etkileri  raporda dikkat çekmektedir. Diğer kriterlerde ortalamalara yakın sonuçlar elde edilmiştir.  Batı Avrupa ekonomileri yasa analizlerinde ise ekonomilerin uluslararsılaşma, yenilik, araştırma geliştirme, inovasyon alanlarında daha etkin oldukları değerlendirilebilir. 

Türkiye’ de Kobilere verilen destekler incelendiğinde destek modelleri açısından yeterli programların yürütüldüğü görülmektedir. Problemlerin kaynağı var olan destek modellerinin işleyişinde yaşanılan problemler, yararlanıcı kitlenin destek modellerini işletmelerin yapılarına uyumunu sağlayamaması, destek unsurlarının maddi unsurlarına odaklanılması  olarak sıralanabilir.  İşletmelerin finans kaynaklarina ulaşım modellerinde çeşitlendirmelere gidilmemesi  ve vadelerin kısa tutulmasının etkileri de mevcuttur.

Türkiye  Kobilere sağlanan devlet desteklerinin yaptırımlarında ve felsefesinde eksiklikler bulunmaktadır. Yapılması gereken işletmeleri işbirliği, uluslararasılaşma, yenilikçilik  ve diğer alanlarda işletmelere yardım sağlanırken dünyadaki kabul görmüş, güncel ilkelerin işletmelere benimsetilebilmesidir. Bu modeller geliştirilebildiği takdirde işletmelerin mevcut düzenlemelerle olan uyum problemleri aşılacak ve işletmeler kendiliğinden süreçlere dahil edilebilecektir.
